// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RssReading.Data;

namespace RssReading.Data.Migrations
{
    [DbContext(typeof(RssContext))]
    partial class RssContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RssReading.Data.Models.RssItemData", b =>
                {
                    b.Property<string>("Title");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("Description");

                    b.Property<string>("Link");

                    b.Property<Guid>("SourceDataId");

                    b.HasKey("Title", "PublishDate");

                    b.HasIndex("SourceDataId");

                    b.ToTable("RssItemDatas");
                });

            modelBuilder.Entity("RssReading.Data.Models.SourceData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SourceDatas");
                });

            modelBuilder.Entity("RssReading.Data.Models.RssItemData", b =>
                {
                    b.HasOne("RssReading.Data.Models.SourceData", "Source")
                        .WithMany("RssItemDatas")
                        .HasForeignKey("SourceDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
